#!/bin/bash

TEST_NAME="$1"

confirmed=0

while [ "$confirmed" -eq 0 ]; do

    if [ -z "${TEST_NAME}" ]; then
	read -e -p "describe your new test briefly: " -i "$tname" TEST_NAME
    fi

    tname="${TEST_NAME// /_}"
    newnum="$(( $(ls -d tests/* | sed 's|^[^/]*/\([0-9]*\)_.*|\1|' | sort -n | tail -n 1 | sed s/^0//) + 1))"
    newname="$(printf "%02d_%s" "${newnum}" "$tname")"

    read -p "your new test will be named tests/$newname. OK? [Y/n]"
    if [ "$REPLY" == "" ] || [ "${REPLY/Y/y}" == "y" ]; then
        confirmed=1
    fi
done

cp -a tests/00_basic "tests/$newname"

# create run script for make check
newscript="test-${newname}.bash"
echo '#!/bin/bash' >"${newscript}"
echo "\${srcdir}/runtests t-${newnum}" >>"${newscript}"
chmod a+x "${newscript}"

echo "You can now edit ${newname}."
echo "When ready, add ${newscript} to TESTS in Makefile.am."
