name: Build mod_gnutls
description: Shared mod_gnutls build action
author: 'fiona.klute@gmx.de'

inputs:
  cc:
    description: 'The compiler to use (CC)'
    required: no
    default: 'gcc'
  configure-options:
    description: 'Additional options to pass to meson setup'
    required: no
    default: ''
  artifact-prefix:
    description: 'Prefix for artifact names'
    required: yes

runs:
  using: composite
  steps:
    - name: network overview
      shell: bash
      run: |
        ip addr show
        cat /etc/hosts
    - name: find usable IPs for tests
      shell: bash
      run: |
        echo "test_ips=$(python3 test/check_test_ips.py -H localhost)" >> ${GITHUB_ENV}
    - name: meson setup
      shell: bash
      run: meson setup -Dtest-ips="${TEST_IPS}" ${{ inputs.configure-options }} build
      env:
        CC: "${{ inputs.cc }}"
        TEST_IPS: "${{ env.test_ips }}"
    - name: meson compile
      shell: bash
      run: meson compile -C build/
    - name: meson test
      shell: bash
      run: meson test -C build/ --verbose
    - name: store test logs
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: ${{ inputs.artifact-prefix }}-test-logs
        path: |
          build/meson-logs/
          build/test/*.log
          build/test/logs/
