#!/bin/bash

TEST_NAME="$1"

confirmed=0

while [ "$confirmed" -eq 0 ]; do

    read -e -p "describe your new test briefly: " -i "$tname" TEST_NAME

    tname="${TEST_NAME// /_}"
    newname="$(printf "%02d_%s" "$(( $(ls -d tests/* | sed 's|^[^/]*/\([0-9]*\)_.*|\1|' | sort -n | tail -n 1 | sed s/^0//) + 1 ))" "$tname")"

    read -p "your new test will be named tests/$newname.  OK [Y/n]? "
    if [ "$REPLY" == "" ] || [ "${REPLY/Y/y}" == "y" ]; then
        confirmed=1
    fi
done

cp -a tests/00_basic "tests/$newname"

printf "You can now edit %s\n" "$newname"
